name: Release Build

on:
  release:
    types: [published]

permissions:
    contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: pingme
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact: pingme
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: pingme.exe

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Archive Binary
        run: |
          cd target/${{ matrix.target }}/release
          zip ${{ matrix.artifact }}-${{ github.ref_name }}-${{ matrix.target }}.zip ${{ matrix.artifact }}

      - name: Upload Release Binary
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/release/${{ matrix.artifact }}-${{ github.ref_name }}-${{ matrix.target }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
